/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DuvidasControl;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class TelaSobreNos extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaSobreNos
     */
    public TelaSobreNos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btDownloadSobre = new javax.swing.JButton();
        btDownloadPSI = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Sobre Nós");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-sobre.png"))); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgSobre.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 121, -1, 212));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgPSI.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 121, -1, 212));

        btDownloadSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-baixar.png"))); // NOI18N
        btDownloadSobre.setText("Download");
        btDownloadSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDownloadSobreActionPerformed(evt);
            }
        });
        getContentPane().add(btDownloadSobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 54, 150, -1));

        btDownloadPSI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-baixar.png"))); // NOI18N
        btDownloadPSI.setText("Download");
        btDownloadPSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDownloadPSIActionPerformed(evt);
            }
        });
        getContentPane().add(btDownloadPSI, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 54, 150, -1));

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-fechar-janela.png"))); // NOI18N
        btSair.setText("SAIR");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        getContentPane().add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 367, 100, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundoInterno.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btDownloadSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDownloadSobreActionPerformed
        
        try {
            DuvidasControl.downloadSobreNos();
        } catch (IOException ex) {
            Logger.getLogger(TelaSobreNos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btDownloadSobreActionPerformed

    private void btDownloadPSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDownloadPSIActionPerformed
        try {
            DuvidasControl.downloadPSI();
        } catch (IOException ex) {
            Logger.getLogger(TelaSobreNos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btDownloadPSIActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDownloadPSI;
    private javax.swing.JButton btDownloadSobre;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
