/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DoadorControl;
import javax.swing.JOptionPane;
import model.Pessoa;
import view.TelaPrincipal;

/**
 *
 * @author karol
 */
public class TelaMenuDoadorDoaRoupa extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaMenuDoadorDoaRoupa
     */
    public TelaMenuDoadorDoaRoupa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtQtdeRoupas = new javax.swing.JTextField();
        btDoarRoupa = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbRoupas = new javax.swing.JTable();
        btRetornar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setTitle("Doador - Doar Roupas");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-blazer.png"))); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Digite a quantidade de peças que deseja doar:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 260, 266, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Seleciona a peça deseja doar:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 62, 260, -1));
        getContentPane().add(txtQtdeRoupas, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 282, 139, -1));

        btDoarRoupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-blazer.png"))); // NOI18N
        btDoarRoupa.setText("DOAR");
        btDoarRoupa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDoarRoupaActionPerformed(evt);
            }
        });
        getContentPane().add(btDoarRoupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 371, 90, -1));

        tbRoupas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Blusa",  new Double(0.0)},
                {"Camisa",  new Double(0.0)},
                {"Casaco",  new Double(0.0)},
                {"Short",  new Double(0.0)},
                {"Bermuda",  new Double(0.0)},
                {"Calça",  new Double(0.0)},
                {"Sapato", null}
            },
            new String [] {
                "Roupas", "Quantidade "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbRoupas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(tbRoupas);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 91, 266, 157));

        btRetornar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-retornar-filled.png"))); // NOI18N
        btRetornar.setText("RETORNAR");
        btRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetornarActionPerformed(evt);
            }
        });
        getContentPane().add(btRetornar, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 371, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundoInterno.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDoarRoupaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDoarRoupaActionPerformed
       if(tbRoupas.getSelectedRowCount()==0){
           JOptionPane.showMessageDialog(null, "Selecione alguma peça!");
       }
       else if(txtQtdeRoupas.getText().equals("")){
           JOptionPane.showMessageDialog(null, "Selecione algum valor!");
       }
        
       else{
           try {
        if(Integer.valueOf(txtQtdeRoupas.getText())>0){
            DoadorControl.salvarBancoRoupas();
            DoadorControl.doarRoupas(tbRoupas.getSelectedRow(),Integer.valueOf(txtQtdeRoupas.getText()));  
         tbRoupas.setValueAt(Pessoa.bancoRoupas2.get(tbRoupas.getSelectedRow()), tbRoupas.getSelectedRow(), 1);
         TelaPrincipal.notifi("Uma pessoa doou "+txtQtdeRoupas.getText()+" roupas!","Nova doaçao");
        }
        else {
            JOptionPane.showMessageDialog(null, "Quantidade inserida inválida");
        }
         }catch (NumberFormatException e) {
                           JOptionPane.showMessageDialog(null, "Digite apenas números inteiros");

           }
       }
    }//GEN-LAST:event_btDoarRoupaActionPerformed

    private void btRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetornarActionPerformed
         this.dispose();
             TelaMenuDoador telaMenuDoa = new TelaMenuDoador();
             TelaPrincipal.painel.add(telaMenuDoa);
             telaMenuDoa.setVisible(true);
    }//GEN-LAST:event_btRetornarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDoarRoupa;
    private javax.swing.JButton btRetornar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    public static javax.swing.JTable tbRoupas;
    private javax.swing.JTextField txtQtdeRoupas;
    // End of variables declaration//GEN-END:variables
}
