/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.TelaPrincipal;

/**
 *
 * @author karol
 */
public class TelaMenuDonatarioVisualizarRecebidos extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaMenuDOnatarioVisualizarRecebidos
     */
    public TelaMenuDonatarioVisualizarRecebidos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btRetornar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtDinheiroRecebido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRoupaRecebida = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Donatário - Dinheiro/Peças Recebidas");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-gorro.png"))); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btRetornar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-retornar-filled.png"))); // NOI18N
        btRetornar.setText("RETORNAR");
        btRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetornarActionPerformed(evt);
            }
        });
        getContentPane().add(btRetornar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 120, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Dinheiro Recebido: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        txtDinheiroRecebido.setEditable(false);
        getContentPane().add(txtDinheiroRecebido, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 80, 42));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Roupas recebidas:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        txtRoupaRecebida.setEditable(false);
        getContentPane().add(txtRoupaRecebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 80, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundoInterno.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetornarActionPerformed
        this.dispose();
        TelaMenuDonatario telaMenuDona = new TelaMenuDonatario();
        TelaPrincipal.painel.add(telaMenuDona);
        telaMenuDona.setVisible(true);
    }//GEN-LAST:event_btRetornarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRetornar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JTextField txtDinheiroRecebido;
    public static javax.swing.JTextField txtRoupaRecebida;
    // End of variables declaration//GEN-END:variables
}
