/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DoadorControl;
import controller.DonatarioControl;
import model.Pessoa;
import view.TelaPrincipal;

/**
 *
 * @author karol
 */
public class TelaMenuDoador extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaMenuDoador
     */
    public TelaMenuDoador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        rbDoarDinheiro = new javax.swing.JRadioButton();
        rbDoarRoupas = new javax.swing.JRadioButton();
        rbVisualizarBancos = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("ACESSAR");

        jButton2.setText("ACESSAR");

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setTitle("Menu Doador");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-bem-estar.png"))); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(rbDoarDinheiro);
        rbDoarDinheiro.setText("Doar Dinheiro");
        rbDoarDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDoarDinheiroActionPerformed(evt);
            }
        });
        getContentPane().add(rbDoarDinheiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 240, -1));

        buttonGroup1.add(rbDoarRoupas);
        rbDoarRoupas.setText("Doar Roupas");
        rbDoarRoupas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDoarRoupasActionPerformed(evt);
            }
        });
        getContentPane().add(rbDoarRoupas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 240, -1));

        buttonGroup1.add(rbVisualizarBancos);
        rbVisualizarBancos.setText("Consultar Bancos(Dinheiro/Roupas)");
        rbVisualizarBancos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVisualizarBancosActionPerformed(evt);
            }
        });
        getContentPane().add(rbVisualizarBancos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 240, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-fechar-janela.png"))); // NOI18N
        jButton3.setText("SAIR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 365, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundoInterno.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbDoarDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDoarDinheiroActionPerformed
        this.dispose();
        TelaMenuDoadorDoaDinheiro telaDoaDinheiro = new TelaMenuDoadorDoaDinheiro();
        TelaPrincipal.painel.add(telaDoaDinheiro);
        telaDoaDinheiro.setVisible(true);
    }//GEN-LAST:event_rbDoarDinheiroActionPerformed

    private void rbDoarRoupasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDoarRoupasActionPerformed
  this.dispose();
        TelaMenuDoadorDoaRoupa telaDoaRoupa = new TelaMenuDoadorDoaRoupa();
        TelaPrincipal.painel.add(telaDoaRoupa);
        telaDoaRoupa.setVisible(true);
        
        DoadorControl.salvarBancoRoupas();
        for(int i=0;i<Pessoa.bancoRoupas2.size();i++){
                TelaMenuDoadorDoaRoupa.tbRoupas.setValueAt(Pessoa.bancoRoupas2.get(i), i, 1);
            }
    }//GEN-LAST:event_rbDoarRoupasActionPerformed

    private void rbVisualizarBancosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVisualizarBancosActionPerformed
        this.dispose();
        TelaMenuDoadorVisualizar telaVisu = new TelaMenuDoadorVisualizar();
        TelaPrincipal.painel.add(telaVisu);
        telaVisu.setVisible(true);
        
        DoadorControl.salvarBancoRoupas();
        DoadorControl.salvarBancoDinheiro();
        
        for(int i=0;i<Pessoa.bancoRoupas2.size();i++){
                TelaMenuDoadorVisualizar.tbRoupasVisu.setValueAt(Pessoa.bancoRoupas2.get(i), i, 1);
            }
        TelaMenuDoadorVisualizar.txtQtdeDin.setText(Double.toString(Pessoa.dinheiroDoado));
    }//GEN-LAST:event_rbVisualizarBancosActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rbDoarDinheiro;
    private javax.swing.JRadioButton rbDoarRoupas;
    private javax.swing.JRadioButton rbVisualizarBancos;
    // End of variables declaration//GEN-END:variables
}
