/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.TelaPrincipal;

/**
 *
 * @author karol
 */
public class TelaMenuDoadorVisualizar extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaMenuDoadorVisualizar
     */
    public TelaMenuDoadorVisualizar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btRetornar = new javax.swing.JButton();
        txtQtdeDin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbRoupasVisu = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Doador - Visualizar Bancos");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-luvas.png"))); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btRetornar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-retornar-filled.png"))); // NOI18N
        btRetornar.setText("RETORNAR");
        btRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetornarActionPerformed(evt);
            }
        });
        getContentPane().add(btRetornar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 368, 120, -1));

        txtQtdeDin.setEditable(false);
        getContentPane().add(txtQtdeDin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 204, 74, 32));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Quantidade de Dinheiro no Banco:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 212, -1, -1));

        tbRoupasVisu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Blusa",  new Double(0.0)},
                {"Camisa",  new Double(0.0)},
                {"Casaco",  new Double(0.0)},
                {"Short",  new Double(0.0)},
                {"Bermuda",  new Double(0.0)},
                {"Calça",  new Double(0.0)},
                {"Sapato", null}
            },
            new String [] {
                "Roupas", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbRoupasVisu.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(tbRoupasVisu);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 539, 130));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundoInterno.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetornarActionPerformed
             this.dispose();
             TelaMenuDoador telaMenuDoa = new TelaMenuDoador();
             TelaPrincipal.painel.add(telaMenuDoa);
             telaMenuDoa.setVisible(true);
    }//GEN-LAST:event_btRetornarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRetornar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTable tbRoupasVisu;
    public static javax.swing.JTextField txtQtdeDin;
    // End of variables declaration//GEN-END:variables
}
