/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.TrocaRoupaControl;
import javax.swing.JOptionPane;
import model.TrocaRoupa;

/**
 *
 * @author karol
 */
public class TelaMenuTrocaRoupaReceber extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaMenuTrocaRoupaReceber
     */
    public TelaMenuTrocaRoupaReceber() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbReceber = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtQtde = new javax.swing.JTextField();
        btReceber = new javax.swing.JButton();
        btRetornar = new javax.swing.JButton();
        txtBonus = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtRecebidas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-camisa.png"))); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbReceber.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Blusa",  new Integer(0)},
                {"Camisa",  new Integer(0)},
                {"Casaco",  new Integer(0)},
                {"Short",  new Integer(0)},
                {"Bermuda",  new Integer(0)},
                {"Calça",  new Integer(0)},
                {"Sapato",  new Integer(0)}
            },
            new String [] {
                "Roupas", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbReceber.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tbReceber);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 140));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Digite a quantidade que deseja Receber:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 280, -1));
        getContentPane().add(txtQtde, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 160, -1));

        btReceber.setText("Receber");
        btReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReceberActionPerformed(evt);
            }
        });
        getContentPane().add(btReceber, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, -1));

        btRetornar.setText("RETORNAR");
        btRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetornarActionPerformed(evt);
            }
        });
        getContentPane().add(btRetornar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 100, -1));

        txtBonus.setEditable(false);
        getContentPane().add(txtBonus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 70, 40));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Bônus de Troca:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Peças Recebidas:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, 20));

        txtRecebidas.setEditable(false);
        getContentPane().add(txtRecebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 80, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundoInterno.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReceberActionPerformed
        try {
            if(tbReceber.getSelectedRowCount()==0){
                JOptionPane.showMessageDialog(null, "Selecione alguma peça!");
            }
            else{
                if(Integer.valueOf(txtQtde.getText())>0){
                    TrocaRoupaControl.serializaBancoRoupas();

                    TrocaRoupaControl.recebimentoDeRoupas(TelaLoginTrocaRoupa.txtLogTrocaLogin.getText(),TelaLoginTrocaRoupa.txtLogTrocaSenha.getText(),tbReceber.getSelectedRow(),Integer.valueOf(txtQtde.getText()));
                    tbReceber.setValueAt(TrocaRoupa.bancoRoupas2.get(tbReceber.getSelectedRow()), tbReceber.getSelectedRow(), 1);

                    String bonus = Integer.toString(TrocaRoupaControl.verBonus(TelaLoginTrocaRoupa.txtLogTrocaLogin.getText(),TelaLoginTrocaRoupa.txtLogTrocaSenha.getText()));
                   txtBonus.setText(bonus);
        
                String recebidas = Integer.toString(TrocaRoupaControl.verRecebidas(TelaLoginTrocaRoupa.txtLogTrocaLogin.getText(),TelaLoginTrocaRoupa.txtLogTrocaSenha.getText()));
                txtRecebidas.setText(recebidas);
                  
                }
                else {

                    JOptionPane.showMessageDialog(null, "Quantidade inserida inválida");
                }
            }
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Digite apenas números inteiros");

        }
    }//GEN-LAST:event_btReceberActionPerformed

    private void btRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetornarActionPerformed
        this.dispose();
        TelaMenuTrocaRoupa telaMenuTroca = new TelaMenuTrocaRoupa();
        TelaPrincipal.painel.add(telaMenuTroca);
        telaMenuTroca.setVisible(true);
    }//GEN-LAST:event_btRetornarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btReceber;
    private javax.swing.JButton btRetornar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tbReceber;
    public static javax.swing.JTextField txtBonus;
    private javax.swing.JTextField txtQtde;
    public static javax.swing.JTextField txtRecebidas;
    // End of variables declaration//GEN-END:variables
}
