/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Exceptions.LoginOuSenhaIncorreto;
import controller.DoadorControl;
import static java.awt.image.ImageObserver.WIDTH;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Pessoa;
import view.TelaPrincipal;

/**
 *
 * @author karol
 */
public class TelaLoginDoador extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaLoginDoador
     */
    public TelaLoginDoador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtLogDoaLogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtLogDoaSenha = new javax.swing.JTextField();
        btLogDoa = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setTitle("Login Doador");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-entrar.png"))); // NOI18N
        setRequestFocusEnabled(false);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVerifyInputWhenFocusTarget(false);
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Login:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 135, -1, -1));

        txtLogDoaLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtLogDoaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 134, 108, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Senha:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 171, -1, -1));

        txtLogDoaSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtLogDoaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 170, 108, -1));

        btLogDoa.setBackground(new java.awt.Color(255, 255, 255));
        btLogDoa.setText("Login");
        btLogDoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btLogDoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogDoaActionPerformed(evt);
            }
        });
        getContentPane().add(btLogDoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 241, 94, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundoInterno.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLogDoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogDoaActionPerformed
 try {
        if(txtLogDoaLogin.getText().equals("") ||txtLogDoaSenha.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha os campos em branco!", "Login não efetivado", WIDTH);  
        }
        else{
           
                DoadorControl.loginDoador(txtLogDoaLogin.getText(), txtLogDoaSenha.getText());
            } 
        
        if(DoadorControl.aux==1){
            this.dispose();
            TelaMenuDoador telaMenuDoa = new TelaMenuDoador();
            TelaPrincipal.painel.add(telaMenuDoa);
            telaMenuDoa.setVisible(true);
        }
 }
    catch (Exceptions.LoginOuSenhaIncorreto a) {
            JOptionPane.showMessageDialog(null, a.getMessage(), "Login não efetivado", WIDTH);
        }
                Pessoa.Inicializar();
    }//GEN-LAST:event_btLogDoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogDoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtLogDoaLogin;
    private javax.swing.JTextField txtLogDoaSenha;
    // End of variables declaration//GEN-END:variables
}
