/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DonatarioControl;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.JOptionPane;
import model.Pessoa;

/**
 *
 * @author karol
 */
public class TelaLoginDonatario extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaLoginDonatario
     */
    public TelaLoginDonatario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtLogDonaSenha = new javax.swing.JTextField();
        btLogDona = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtLogDonaLogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Login Donatário");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-entrar.png"))); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Senha:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 164, -1, -1));

        txtLogDonaSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtLogDonaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 163, 108, -1));

        btLogDona.setBackground(new java.awt.Color(255, 255, 255));
        btLogDona.setText("Login");
        btLogDona.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btLogDona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogDonaActionPerformed(evt);
            }
        });
        getContentPane().add(btLogDona, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 234, 94, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Login:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 128, -1, -1));

        txtLogDonaLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtLogDonaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 127, 108, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundoInterno.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLogDonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogDonaActionPerformed
try {
        if(txtLogDonaLogin.getText().equals("") ||txtLogDonaSenha.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha os campos em branco!", "Cadastro não efetivado", WIDTH);
        }
        else{
            DonatarioControl.loginDonatario(txtLogDonaLogin.getText(), txtLogDonaSenha.getText());
        }
        if(DonatarioControl.aux==1){
            this.dispose();
            TelaMenuDonatario telaMenuDona = new TelaMenuDonatario();
            getParent().add(telaMenuDona);
            telaMenuDona.setVisible(true);
        }
        else if (DonatarioControl.aux==0){
            JOptionPane.showMessageDialog(null, "Login e/ou Senha incorretos!", "Login não efetivado", WIDTH);
        }
        }catch (Exceptions.LoginOuSenhaIncorreto a) {
            JOptionPane.showMessageDialog(null, a.getMessage(), "Login não efetivado", WIDTH);
        }
               Pessoa.Inicializar();
    }//GEN-LAST:event_btLogDonaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogDona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JTextField txtLogDonaLogin;
    public static javax.swing.JTextField txtLogDonaSenha;
    // End of variables declaration//GEN-END:variables
}
