/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DonatarioControl;
import javax.swing.JOptionPane;

/**
 *
 * @author karol
 */
public class TelaCadastroDonatario extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroDonatario
     */
    public TelaCadastroDonatario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        botaoCadDona = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        rbFisica = new javax.swing.JRadioButton();
        rbJuridica = new javax.swing.JRadioButton();
        txtCadDonaSenha2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCadDonaSenha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCadDonaLogin = new javax.swing.JTextField();
        txtCadDonaNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setTitle("Cadastro Donatário");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-adicionar-usuário-masculino.png"))); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoCadDona.setText("Cadastrar");
        botaoCadDona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadDonaActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCadDona, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 330, 120, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Pessoa:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        buttonGroup1.add(rbFisica);
        rbFisica.setText("Física");
        rbFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFisicaActionPerformed(evt);
            }
        });
        getContentPane().add(rbFisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 80, -1));

        buttonGroup1.add(rbJuridica);
        rbJuridica.setText("Jurídica");
        getContentPane().add(rbJuridica, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));
        getContentPane().add(txtCadDonaSenha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 203, 316, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Login:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 135, -1, -1));
        getContentPane().add(txtCadDonaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 167, 316, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Senha:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 171, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Confirmar Senha:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 207, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nome Completo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 97, -1, -1));
        getContentPane().add(txtCadDonaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 131, 316, -1));
        getContentPane().add(txtCadDonaNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 93, 316, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundoInterno.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadDonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadDonaActionPerformed

        if(txtCadDonaNome.getText().equals("") ||txtCadDonaLogin.getText().equals("")|| txtCadDonaSenha.getText().equals("") || txtCadDonaSenha2.getText().equals("") || !rbFisica.isSelected() && !rbJuridica.isSelected() ){
            JOptionPane.showMessageDialog(null, "Preencha os campos em branco!", "Cadastro não efetivado", WIDTH);
        }
        else if(txtCadDonaSenha.getText().equals(txtCadDonaSenha2.getText())){

            if(rbFisica.isSelected()){
                DonatarioControl.cadastroDonatario(txtCadDonaLogin.getText(), txtCadDonaSenha.getText(),1);
            }
            else if(rbJuridica.isSelected()){
                DonatarioControl.cadastroDonatario(txtCadDonaLogin.getText(), txtCadDonaSenha.getText(),2);
            }
            if(DonatarioControl.aux==1){
                this.dispose();
            }
        }
         else if(!txtCadDonaSenha.getText().equals(txtCadDonaSenha2.getText())){
        JOptionPane.showMessageDialog(null, "Confirmação de Senha incorreta", "Cadastro não efetivado", WIDTH);
        }
    }//GEN-LAST:event_botaoCadDonaActionPerformed

    private void rbFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFisicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFisicaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadDona;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JRadioButton rbFisica;
    public static javax.swing.JRadioButton rbJuridica;
    private javax.swing.JTextField txtCadDonaLogin;
    public static javax.swing.JTextField txtCadDonaNome;
    private javax.swing.JTextField txtCadDonaSenha;
    private javax.swing.JTextField txtCadDonaSenha2;
    // End of variables declaration//GEN-END:variables
}
