/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.TrocaRoupaControl;
import javax.swing.JOptionPane;
import model.TrocaRoupa;

/**
 *
 * @author karol
 */
public class TelaLoginTrocaRoupa extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaLoginTrocaRoupa
     */
    public TelaLoginTrocaRoupa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtLogTrocaLogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtLogTrocaSenha = new javax.swing.JTextField();
        btLogTroca = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Login Troca-Roupa");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-blazer.png"))); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Login:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 135, -1, -1));

        txtLogTrocaLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtLogTrocaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 134, 108, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Senha:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 171, -1, -1));

        txtLogTrocaSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtLogTrocaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 170, 108, -1));

        btLogTroca.setBackground(new java.awt.Color(255, 255, 255));
        btLogTroca.setText("Login");
        btLogTroca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btLogTroca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogTrocaActionPerformed(evt);
            }
        });
        getContentPane().add(btLogTroca, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 241, 94, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundoInterno.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLogTrocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogTrocaActionPerformed
        try {
            if(txtLogTrocaLogin.getText().equals("") ||txtLogTrocaSenha.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Preencha os campos em branco!", "Login não efetivado", WIDTH);
            }
            else{

                TrocaRoupaControl.loginTrocaRoupa(txtLogTrocaLogin.getText(), txtLogTrocaSenha.getText());
            }

            if(TrocaRoupaControl.aux==1){
                this.dispose();
                TelaMenuTrocaRoupa telaMenuTroca= new TelaMenuTrocaRoupa();
                TelaPrincipal.painel.add(telaMenuTroca);
                telaMenuTroca.setVisible(true);
            }
        }
        catch (Exceptions.LoginOuSenhaIncorreto a) {
            JOptionPane.showMessageDialog(null, a.getMessage(), "Login não efetivado", WIDTH);
        }
        
        TrocaRoupa.bancoDeRoupasInicializar();
    }//GEN-LAST:event_btLogTrocaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogTroca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JTextField txtLogTrocaLogin;
    public static javax.swing.JTextField txtLogTrocaSenha;
    // End of variables declaration//GEN-END:variables
}
