/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.TrocaRoupaControl;
import javax.swing.JOptionPane;
import model.TrocaRoupa;
import static view.TelaMenuDonatarioRecebeRoupa.tbRoupasReceber;

/**
 *
 * @author karol
 */
public class TelaMenuTrocaRoupaAdiciona extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaMenuTrocaRoupa
     */
    public TelaMenuTrocaRoupaAdiciona() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbAdd = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtQtde = new javax.swing.JTextField();
        btAdd = new javax.swing.JButton();
        btRetornar = new javax.swing.JButton();
        txtDadas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBonus = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Menu Troca-Roupa");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-calção.png"))); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbAdd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Blusa",  new Integer(0)},
                {"Camisa",  new Integer(0)},
                {"Casaco",  new Integer(0)},
                {"Short",  new Integer(0)},
                {"Bermuda",  new Integer(0)},
                {"Calça",  new Integer(0)},
                {"Sapato",  new Integer(0)}
            },
            new String [] {
                "Roupas", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbAdd.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tbAdd);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 130));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Digite a quantidade que deseja colocar no Banco:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 280, -1));
        getContentPane().add(txtQtde, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 160, -1));

        btAdd.setText("Adicionar");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });
        getContentPane().add(btAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, -1));

        btRetornar.setText("RETORNAR");
        btRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetornarActionPerformed(evt);
            }
        });
        getContentPane().add(btRetornar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 100, -1));

        txtDadas.setEditable(false);
        getContentPane().add(txtDadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 70, 30));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Roupas dadas até agora:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Bônus de Troca:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        txtBonus.setEditable(false);
        getContentPane().add(txtBonus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 70, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundoInterno.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetornarActionPerformed
        this.dispose();
             TelaMenuTrocaRoupa telaMenuTroca = new TelaMenuTrocaRoupa();
             TelaPrincipal.painel.add(telaMenuTroca);
             telaMenuTroca.setVisible(true);
    }//GEN-LAST:event_btRetornarActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        try {
        if(tbAdd.getSelectedRowCount()==0){
           JOptionPane.showMessageDialog(null, "Selecione alguma peça!");
       }
        else{
        if(Integer.valueOf(txtQtde.getText())>0){
            TrocaRoupaControl.serializaBancoRoupas();
           
            TrocaRoupaControl.trocaDeRoupas(TelaLoginTrocaRoupa.txtLogTrocaLogin.getText(),TelaLoginTrocaRoupa.txtLogTrocaSenha.getText(),tbAdd.getSelectedRow(),Integer.valueOf(txtQtde.getText()));  
            tbAdd.setValueAt(TrocaRoupa.bancoRoupas2.get(tbAdd.getSelectedRow()), tbAdd.getSelectedRow(), 1);
            TelaPrincipal.notifi("Uma pessoa doou "+txtQtde.getText()+" roupas!","Nova doaçao");
            
            String dadas = Integer.toString(TrocaRoupaControl.verDadas(TelaLoginTrocaRoupa.txtLogTrocaLogin.getText(),TelaLoginTrocaRoupa.txtLogTrocaSenha.getText()));
            txtDadas.setText(dadas);
            
            String bonus = Integer.toString(TrocaRoupaControl.verBonus(TelaLoginTrocaRoupa.txtLogTrocaLogin.getText(),TelaLoginTrocaRoupa.txtLogTrocaSenha.getText()));
            TelaMenuTrocaRoupaAdiciona.txtBonus.setText(bonus);
        }
        else {
            
            JOptionPane.showMessageDialog(null, "Quantidade inserida inválida");
        }
        }
        }catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(null, "Digite apenas números inteiros");

        }
    }//GEN-LAST:event_btAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btRetornar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tbAdd;
    public static javax.swing.JTextField txtBonus;
    public static javax.swing.JTextField txtDadas;
    private javax.swing.JTextField txtQtde;
    // End of variables declaration//GEN-END:variables
}
