/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.TelaPrincipal;

/**
 *
 * @author karol
 */
public class TelaMenuDonatarioVisualizar extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaMenuDonatarioVisualizar
     */
    public TelaMenuDonatarioVisualizar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtQtdeDin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbRoupasVisu = new javax.swing.JTable();
        btRetornar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Donatário - Visualizar Bancos");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-blazer.png"))); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtQtdeDin.setEditable(false);
        getContentPane().add(txtQtdeDin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 204, 74, 32));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Quantidade de Dinheiro no Banco:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 212, -1, -1));

        tbRoupasVisu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Blusa",  new Double(0.0)},
                {"Camisa",  new Double(0.0)},
                {"Casaco",  new Double(0.0)},
                {"Short",  new Double(0.0)},
                {"Bermuda",  new Double(0.0)},
                {"Calça",  new Double(0.0)},
                {"Sapato", null}
            },
            new String [] {
                "Roupas", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbRoupasVisu.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane5.setViewportView(tbRoupasVisu);

        jTabbedPane2.addTab("Banco de Roupas", jScrollPane5);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 541, 168));

        btRetornar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-retornar-filled.png"))); // NOI18N
        btRetornar.setText("RETORNAR");
        btRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetornarActionPerformed(evt);
            }
        });
        getContentPane().add(btRetornar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 358, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundoInterno.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetornarActionPerformed
        this.dispose();
        TelaMenuDonatario telaMenuDona = new TelaMenuDonatario();
        TelaPrincipal.painel.add(telaMenuDona);
        telaMenuDona.setVisible(true);
    }//GEN-LAST:event_btRetornarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRetornar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane2;
    public static javax.swing.JTable tbRoupasVisu;
    public static javax.swing.JTextField txtQtdeDin;
    // End of variables declaration//GEN-END:variables
}
