/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.TrocaRoupaControl;
import javax.swing.JOptionPane;

/**
 *
 * @author karol
 */
public class TelaCadastroTrocaRoupa extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroTrocaRoupa
     */
    public TelaCadastroTrocaRoupa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoCadTroca = new javax.swing.JButton();
        txtCadTrocaSenha2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCadTrocaSenha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCadTrocaLogin = new javax.swing.JTextField();
        txtCadTrocaNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Cadastro Troca-Roupa");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-adicionar-usuário-masculino.png"))); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoCadTroca.setText("Cadastrar");
        botaoCadTroca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadTrocaActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCadTroca, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 324, 120, -1));
        getContentPane().add(txtCadTrocaSenha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 203, 314, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Login:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 135, -1, -1));
        getContentPane().add(txtCadTrocaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 167, 316, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Senha:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 171, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Confirmar Senha:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 207, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nome Completo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 97, -1, -1));
        getContentPane().add(txtCadTrocaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 131, 316, -1));
        getContentPane().add(txtCadTrocaNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 93, 316, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundoInterno.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadTrocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadTrocaActionPerformed

        if(txtCadTrocaNome.getText().equals("") ||txtCadTrocaLogin.getText().equals("")|| txtCadTrocaSenha.getText().equals("") || txtCadTrocaSenha2.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha os campos em branco!", "Cadastro não efetivado", WIDTH);
        }
        else if(txtCadTrocaSenha.getText().equals(txtCadTrocaSenha2.getText())){

                TrocaRoupaControl.cadastroTrocaRoupa(txtCadTrocaLogin.getText(), txtCadTrocaSenha.getText());
            if(TrocaRoupaControl.aux==1){
                this.dispose();
            }
        }
        else if(!txtCadTrocaSenha.getText().equals(txtCadTrocaSenha2.getText())){
            JOptionPane.showMessageDialog(null, "Confirmação de Senha incorreta", "Cadastro não efetivado", WIDTH);
        }
    }//GEN-LAST:event_botaoCadTrocaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadTroca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCadTrocaLogin;
    private javax.swing.JTextField txtCadTrocaNome;
    private javax.swing.JTextField txtCadTrocaSenha;
    private javax.swing.JTextField txtCadTrocaSenha2;
    // End of variables declaration//GEN-END:variables
}
