/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DonatarioControl;
import javax.swing.JOptionPane;
import model.Donatario;
import model.Pessoa;
import static view.TelaMenuDonatarioRecebeRoupa.txtLimitePecas;
import view.TelaPrincipal;

/**
 *
 * @author karol
 */
public class TelaMenuDonatario extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaMenuDonatario
     */
    public TelaMenuDonatario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbBancoDin = new javax.swing.JRadioButton();
        rbBancoRoupa = new javax.swing.JRadioButton();
        rbVisualizar = new javax.swing.JRadioButton();
        btRecebidos = new javax.swing.JRadioButton();
        btSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Menu Donatário");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-voluntariado-2.png"))); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(rbBancoDin);
        rbBancoDin.setText("Banco de Dinheiro");
        rbBancoDin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBancoDinActionPerformed(evt);
            }
        });
        getContentPane().add(rbBancoDin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 260, -1));

        buttonGroup1.add(rbBancoRoupa);
        rbBancoRoupa.setText("Banco de Roupas");
        rbBancoRoupa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBancoRoupaActionPerformed(evt);
            }
        });
        getContentPane().add(rbBancoRoupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 260, -1));

        buttonGroup1.add(rbVisualizar);
        rbVisualizar.setText("Visualizar Bancos(Dinheiro/Roupas)");
        rbVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVisualizarActionPerformed(evt);
            }
        });
        getContentPane().add(rbVisualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 260, 30));

        buttonGroup1.add(btRecebidos);
        btRecebidos.setText("Visualizar Recebidos(Dinheiro/Roupas)");
        btRecebidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRecebidosActionPerformed(evt);
            }
        });
        getContentPane().add(btRecebidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 260, -1));

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-fechar-janela.png"))); // NOI18N
        btSair.setText("SAIR");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        getContentPane().add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundoInterno.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbBancoDinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBancoDinActionPerformed
       this.dispose();
        TelaMenuDonatarioRecebeDinheiro telaRecebeDinheiro = new TelaMenuDonatarioRecebeDinheiro();
        TelaPrincipal.painel.add(telaRecebeDinheiro);
        telaRecebeDinheiro.setVisible(true);
        
        DonatarioControl.salvarBancoDinheiro();
        
        String limiteDinheiro = Double.toString(DonatarioControl.limiteDinheiro());
        TelaMenuDonatarioRecebeDinheiro.txtLimite.setText(limiteDinheiro);
        
        String totalDinheiro = Double.toString(Pessoa.dinheiroDoado);
        TelaMenuDonatarioRecebeDinheiro.txtValorDisp.setText(totalDinheiro); 
    }//GEN-LAST:event_rbBancoDinActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void rbBancoRoupaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBancoRoupaActionPerformed
       this.dispose();
        TelaMenuDonatarioRecebeRoupa telaRecebeRoupa = new TelaMenuDonatarioRecebeRoupa();
        TelaPrincipal.painel.add(telaRecebeRoupa);
        telaRecebeRoupa.setVisible(true);
        
        String recebidas = Integer.toString(DonatarioControl.verRoupasRecebidas(TelaLoginDonatario.txtLogDonaLogin.getText(),TelaLoginDonatario.txtLogDonaSenha.getText()));
        TelaMenuDonatarioRecebeRoupa.txtRecebidas.setText(recebidas);
        
         String limite = Integer.toString(DonatarioControl.limiteRoupas());
        txtLimitePecas.setText(limite);
        
        DonatarioControl.salvarBancoRoupas();
        for(int i=0;i<Pessoa.bancoRoupas2.size();i++){
                TelaMenuDonatarioRecebeRoupa.tbRoupasReceber.setValueAt(Pessoa.bancoRoupas2.get(i), i, 1);
            }
    }//GEN-LAST:event_rbBancoRoupaActionPerformed

    private void rbVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVisualizarActionPerformed
        this.dispose();
        TelaMenuDonatarioVisualizar telaVisualizar = new TelaMenuDonatarioVisualizar();
        TelaPrincipal.painel.add(telaVisualizar);
        telaVisualizar.setVisible(true);
        DonatarioControl.salvarBancoRoupas();
        DonatarioControl.salvarBancoDinheiro();
        for(int i=0;i<Pessoa.bancoRoupas2.size();i++){
                TelaMenuDonatarioVisualizar.tbRoupasVisu.setValueAt(Pessoa.bancoRoupas2.get(i), i, 1);
            }
         String dinheiroDoado = Double.toString(Pessoa.dinheiroDoado);
        TelaMenuDonatarioVisualizar.txtQtdeDin.setText(dinheiroDoado);
    }//GEN-LAST:event_rbVisualizarActionPerformed

    private void btRecebidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRecebidosActionPerformed
         this.dispose();
        TelaMenuDonatarioVisualizarRecebidos telaVerRecebidos = new TelaMenuDonatarioVisualizarRecebidos();
        TelaPrincipal.painel.add(telaVerRecebidos);
        telaVerRecebidos.setVisible(true);
      
        String dinheiroRecebido = Double.toString(DonatarioControl.verDinheiroRecebido(TelaLoginDonatario.txtLogDonaLogin.getText(),TelaLoginDonatario.txtLogDonaSenha.getText()));
        TelaMenuDonatarioVisualizarRecebidos.txtDinheiroRecebido.setText(dinheiroRecebido);
        
        String roupaRecebida = Integer.toString(DonatarioControl.verRoupasRecebidas(TelaLoginDonatario.txtLogDonaLogin.getText(),TelaLoginDonatario.txtLogDonaSenha.getText()));
        TelaMenuDonatarioVisualizarRecebidos.txtRoupaRecebida.setText(roupaRecebida);
        
        
    }//GEN-LAST:event_btRecebidosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btRecebidos;
    private javax.swing.JButton btSair;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rbBancoDin;
    private javax.swing.JRadioButton rbBancoRoupa;
    private javax.swing.JRadioButton rbVisualizar;
    // End of variables declaration//GEN-END:variables
}
