/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DoadorControl;
import javax.swing.JOptionPane;
import view.TelaPrincipal;

/**
 *
 * @author karol
 */
public class TelaMenuDoadorDoaDinheiro extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaMenuDoadorDoaDinheiro
     */
    public TelaMenuDoadorDoaDinheiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbQuantias = new javax.swing.JComboBox<>();
        btDoarDin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtDoacao = new javax.swing.JButton();
        btRetornar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Doador - Doar Dinheiro");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-receber-dinheiro.png"))); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Escolha a quantidade de dinheiro que deseja doar:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 92, -1, -1));

        cbQuantias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "5", "10", "50", "100", "200", "400", "800", "Outro" }));
        cbQuantias.setRequestFocusEnabled(false);
        cbQuantias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbQuantiasActionPerformed(evt);
            }
        });
        getContentPane().add(cbQuantias, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 114, -1));

        btDoarDin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-bem-estar.png"))); // NOI18N
        btDoarDin.setText("Doar");
        btDoarDin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDoarDinActionPerformed(evt);
            }
        });
        getContentPane().add(btDoarDin, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 110, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Dinheiro a ser Doado:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 209, -1, -1));
        getContentPane().add(txtDoacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 199, 92, 37));

        btRetornar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-retornar-filled.png"))); // NOI18N
        btRetornar.setText("RETORNAR");
        btRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetornarActionPerformed(evt);
            }
        });
        getContentPane().add(btRetornar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 120, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundoInterno.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbQuantiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbQuantiasActionPerformed
           try {
        if(cbQuantias.getSelectedItem().equals("Outro")){
        String numero = JOptionPane.showInputDialog("Digite o valor desejado");
        
        int number = Integer.parseInt(numero);
         String quantia = Integer.toString(number);
        txtDoacao.setText(quantia);
        }
        else {
            txtDoacao.setText(cbQuantias.getSelectedItem().toString());
        }
        }catch(NumberFormatException e) {
                       JOptionPane.showMessageDialog(null, "Digite apenas números inteiros");
        }
    }//GEN-LAST:event_cbQuantiasActionPerformed

    private void btDoarDinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDoarDinActionPerformed
        if(txtDoacao.getText().equals("Selecione")){
            JOptionPane.showMessageDialog(null, "Por favor escolha um valor para ser doado!");
        } 
        else{
         String valor = txtDoacao.getText();
         valor = valor.replace(",", ".");
         Double valorDouble = Double.parseDouble(valor);
         DoadorControl.doarDinheiro(valorDouble);
         TelaPrincipal.notifi("Uma pessoa doou "+valorDouble+"R$","Nova doaçao");
        }
        
    }//GEN-LAST:event_btDoarDinActionPerformed

    private void btRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetornarActionPerformed
       this.dispose();
             TelaMenuDoador telaMenuDoa = new TelaMenuDoador();
             TelaPrincipal.painel.add(telaMenuDoa);
             telaMenuDoa.setVisible(true);
    }//GEN-LAST:event_btRetornarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDoarDin;
    private javax.swing.JButton btRetornar;
    private javax.swing.JComboBox<String> cbQuantias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton txtDoacao;
    // End of variables declaration//GEN-END:variables
}
