/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.TrocaRoupaControl;
import model.TrocaRoupa;

/**
 *
 * @author karol
 */
public class TelaMenuTrocaRoupa extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaMenuTrocaRoupa
     */
    public TelaMenuTrocaRoupa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbAdicionarRoupa = new javax.swing.JRadioButton();
        rbReceberRoupa = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-bermuda-longa.png"))); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(rbAdicionarRoupa);
        rbAdicionarRoupa.setText("Adicionar Roupas");
        rbAdicionarRoupa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAdicionarRoupaActionPerformed(evt);
            }
        });
        getContentPane().add(rbAdicionarRoupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 153, 240, -1));

        buttonGroup1.add(rbReceberRoupa);
        rbReceberRoupa.setText("Receber Roupas");
        rbReceberRoupa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbReceberRoupaActionPerformed(evt);
            }
        });
        getContentPane().add(rbReceberRoupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 193, 240, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-fechar-janela.png"))); // NOI18N
        jButton3.setText("SAIR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 365, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundoInterno.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbAdicionarRoupaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAdicionarRoupaActionPerformed
        this.dispose();
        TelaMenuTrocaRoupaAdiciona telaTrocaAdd = new TelaMenuTrocaRoupaAdiciona();
        TelaPrincipal.painel.add(telaTrocaAdd);
        telaTrocaAdd.setVisible(true);
        
        String dadas = Integer.toString(TrocaRoupaControl.verDadas(TelaLoginTrocaRoupa.txtLogTrocaLogin.getText(),TelaLoginTrocaRoupa.txtLogTrocaSenha.getText()));
        TelaMenuTrocaRoupaAdiciona.txtDadas.setText(dadas);
        
        String bonus = Integer.toString(TrocaRoupaControl.verBonus(TelaLoginTrocaRoupa.txtLogTrocaLogin.getText(),TelaLoginTrocaRoupa.txtLogTrocaSenha.getText()));
        TelaMenuTrocaRoupaAdiciona.txtBonus.setText(bonus);
        
        TrocaRoupaControl.desserializaBancoRoupas();
        for(int i=0;i<TrocaRoupa.bancoRoupas2.size();i++){
            TelaMenuTrocaRoupaAdiciona.tbAdd.setValueAt(TrocaRoupa.bancoRoupas2.get(i), i, 1);
        }
    }//GEN-LAST:event_rbAdicionarRoupaActionPerformed

    private void rbReceberRoupaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbReceberRoupaActionPerformed
        this.dispose();
        TelaMenuTrocaRoupaReceber telaTrocaRecebe = new TelaMenuTrocaRoupaReceber();
        TelaPrincipal.painel.add(telaTrocaRecebe);
        telaTrocaRecebe.setVisible(true);
        
        String bonus = Integer.toString(TrocaRoupaControl.verBonus(TelaLoginTrocaRoupa.txtLogTrocaLogin.getText(),TelaLoginTrocaRoupa.txtLogTrocaSenha.getText()));
        TelaMenuTrocaRoupaReceber.txtBonus.setText(bonus);
        
        String recebidas = Integer.toString(TrocaRoupaControl.verRecebidas(TelaLoginTrocaRoupa.txtLogTrocaLogin.getText(),TelaLoginTrocaRoupa.txtLogTrocaSenha.getText()));
        TelaMenuTrocaRoupaReceber.txtRecebidas.setText(recebidas);

        TrocaRoupaControl.desserializaBancoRoupas();
        for(int i=0;i<TrocaRoupa.bancoRoupas2.size();i++){
            TelaMenuTrocaRoupaReceber.tbReceber.setValueAt(TrocaRoupa.bancoRoupas2.get(i), i, 1);
        }
    }//GEN-LAST:event_rbReceberRoupaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rbAdicionarRoupa;
    private javax.swing.JRadioButton rbReceberRoupa;
    // End of variables declaration//GEN-END:variables
}
